:imagedir: img/

= Documentation for developers

This is the technical documentation for developers. One can find here every necessary info on the code that has been written and the one to write.

---

== Task list

* [x] main function

* [x] Logger class

* [ ] Game class

* [ ] Options class

* [ ] Screen class

* [x] ResourceHolder class

* [ ] ResourceManager class



== Program entry

link:base/main.adoc[main.adoc]

=== Files:

* link:../src/main.cpp[src/main.cpp]

=== The main function:

* creates a new *Logger* object

* creates a new *Game* object with the new *Logger* object

* intializes the Game

* runs the Game

.main function
[source, C++]
----
int main()
{
    logger = new Logger();
    game = new Game(logger);

    game.init();
    game.run();
}
----



== Logger

link:base/logger.adoc[logger.adoc]

=== Files:

* link:../include/Logger.h[include/Logger.h]

* link:../src/Logger.cpp[src/Logger.cpp]

=== The Logger class:

* is responsible for logging the console output into a txt file

* the log(String str) method append a new line to the log file and displays it in the console

* the log file is latestlog.txt at the root of the program

.Logger class
[source, C++]
----
class Logger
{
public:
    void log(String str);
    
private:
    FileType logfile;
};

void Logger::log(String str)
{
    logfile.append(str);
    std::cout<<str<<std::endl;
}
----



== Game

link:base/game.adoc[game.adoc]

=== Files:

* link:../include/Game.h[include/Game.h]

* link:../src/Game.cpp[src/Game.cpp]

=== The Game class:

* is the master class of the game.

* initializes the game by loading user settings

* handles the game loop

* handles the different screens

* passes the inputs

* updates the screens

* renders the screens

.Game class
[source, C++]
----
class Game
{
public:
    Game();
    void init();
    void run();

private:
    void processEvents();
    void update();
    void render();

private:
    sf::RenderWindow mWindow;
};
----



== Options

link:base/options.adoc[options.adoc]

=== Files:

* link:../include/Options.h[include/Options.h]

* link:../src/Options.cpp[src/Options.cpp]

=== The Options class:

* stores the options variables

* creates default settings on construction

* can be linked to a file with load()

* can store settings to the link file with save()

.Options class
[source, C++]
----
class Options
{
public:
    Options();
    void load();
    void save();

private:
    FileType optionsFile;
    Type1 mOption1;
    Type2 mOption2;
    ...
}
----



== Screen

link:screens/screen.adoc[screen.adoc]

=== Files:

* link:../include/Screens/Screen.h[include/Screens/Screen.h]

* link:../src/Screens/Screen.cpp[include/Screens/Screen.cpp]

=== The Screen class:

* is a virtual class

* is the base class to create specific screens

* can be initialized to load and setup default assets

* can process events, update and render through the corresponding methods

* can block further event processing, updates or renders or not (depend on screen type and cannot be changed)

.Screen class
[source, C++]
----
class Screen
{
public:
    Screen();
    virtual void init();
    virtual void processEvents();
    virtual void update();
    virtual void render();

private:
    const bool blockEvents;
    const bool blockUpdate;
    const bool blockRender;
}
----



== Resource holding

link:base/resourceHolder.adoc[resourceHolder.adoc]

=== Files:

* link:../include/ResourceHolder.h[include/ResourceHolder.h]

* link:../src/ResourceHolder.cpp[src/ResourceHolder.cpp]

=== The ResourceHolder class:

* is a template class

* hold resources (textures, audio, etc ...) in a map

* can load a resource with a specific identifier

* provide access to the resource using the identifier

.ResourceHolder class
[source, C++]
----
template <typename Resource, typename Identifier>
class ResourceHolder
{
public:
    void load(Identifier id, std::string filename);
    const Resource& get(Identifier id) const;

private:
    std::map<Identifier, std::unique_ptr<Resource>> mResourceMap;
}
----



== Resource management

link:base/resourceManager.adoc[resourceManager.adoc]

=== Files:

* link:../include/ResourceManager.h[include/ResourceManager.h]

* link:../src/ResourceManager.cpp[src/ResourceManager.cpp]

=== The ResourceManager class:

* stores the different resource holding instances

* passes the load requests by

* passes the get requests by

* manage resource types automaticaly

.ResourceManager class
[source, C++]
----
class ResourceManager
{
public:
    ResourceManager(Logger& logger);
    void load(Identifier_1 id_1, const std::string& filename);
    const Resource_1& get(Identifier_1 id_1) const;
    void load(Identifier_2 id_2, const std::string& filename);
    const Resource_2& get(Identifier_2 id_2) const;
    ...

private:
    ResourceHolder<Resource_1, Identifier_1> mResource_1Holder;
    ResourceHolder<Resource_2, Identifier_2> mResource_2Holder;
    ...
}
----



== Loading screen

link:screens/loadingScreen.adoc[loadingScreen.adoc]

=== Files:

* link:../include/LoadingScreen.h[include/LoadingScreen.h]

* link:../src/LoadingScreen.cpp[src/LoadingScreen.cpp]

=== The LoadingScreen class:

* inherits the Screen class

* handle loading resources and displaying it

* can register resource to load

* can process resource to load

* store requests as a pair containing the identifier and the filename

.LoadingScreen class
[source, C++]
----
class LoadingScreen : public Screen
{
public:
    LoadingScreen();
    void processEvents();
    void update();
    void render();
    template <typename Identifier>
    void register(Identifier id, const std::string& filename);
}
----



== Task and LoadingTask

link:misc/task.adoc[task.adoc]

=== Files:

* link:../include/Misc/Task.h[include/Misc/Task.h]

* link:../inlcude/Misc/LoadingTask.h[include/Misc/LoadingTask.h]

* link:../include/Misc/LoadingTask.inl[include/Misc/LoadingTask.inl]

* link:../src/Misc/Task.cpp[src/Misc/Task.cpp]

=== The Task class:

* is virtual

* giva access to an identifier and a filename

.Task class
[source, C++]
----
class Task
{
public:
    virtual auto getId();
    virtual std::string& getFileName();
}
----

=== The LoadingTask class:

* inherits task

* is a template class

* stores a pair of Identifier and std::string

.LoadingTask class
[source, C++]
----
template<typename Identifier>
class LoadingTask : public Task
{
public:
    LoadingTask(Identifier id, std::string filename);
    Identifier getId();
    std::string& getFileName();

private:
    Identifier mId;
    std::string mFileName;
}
----

=== The loading::make_task function template:

* construct a LoadingTask object

* the template types can be implicitly deduced from the arguments passed to make_task

.loading::make_task function
[source, C++]
----
namespace loading
{
    template<class T1, class T2>
    LoadingTask<T1, T2> make_task(T1 x, T2 y)
    {
        return LoadingTask<T1, T2>(x, y);
    }
}
----


