:imagedir: img/

= Documentation for developers

This is the technical documentation for developers. One can find here every necessary info on the code that has been written and the one to write.

---

== Program entry

link:base/main.adoc[main.adoc]

=== Files:

* link:../src/main.cpp[src/main.cpp]

=== The main function:

* creates a new *Logger* object

* creates a new *Game* object with the new *Logger* object

* intializes the Game

* runs the Game

.main function
[source, C++]
----
int main()
{
    logger = new Logger();
    game = new Game(logger);

    game.init();
    game.run();
}
----



== Logger

link:base/logger.adoc[logger.adoc]

=== Files:

* link:../include/logger.h[include/logger.h]

* link:../src/logger.cpp[src/logger.cpp]

=== The logger class:

* is responsible for logging the console output into a txt file

* the log(String str) method append a new line to the log file and displays it in the console

* the log file is latestlog.txt at the root of the program

.Logger class
[source, C++]
----
class Logger
{
public:
    void log(String str);
    
private:
    FileType logfile;
};

void Logger::log(String str)
{
    logfile.append(str);
    std::cout<<str<<std::endl;
}
----



== Game

link:base/game.adoc[game.adoc]

=== Files:

* link:../include/game.h[include/game.h]

* link:../src/game.cpp[src/game.cpp]

=== The game class:

* is the master class of the game.

* initializes the game by loading user settings (returns 1 if something went wrong)

* handles the game loop

* handles the different screens

* passes the inputs

* updates the screens

* renders the screens

.Game class
[source, C++]
----
class Game
{
public:
    Game();
    int init();
    void run();

private:
    void processEvents();
    void update();
    void render();

private:
    sf::RenderWindow mWindow;
};
----


