:imagedir: img/

= Documentation for developers

This is the technical documentation for developers. One can find here every necessary info on the code that has been written and the one to write.

---

== Program entry
link:base/main.adoc[main.adoc]

The main function:

* creates a new *Logger* object
* creates a new *Game* object with the new *Logger* object
* intializes the Game
* runs the Game

.main function
[source, C++]
----
int main()
{
    logger = new Logger();
    game = new Game(logger);

    game.init();
    game.run();
}
----



== Logger class
link:base/logger.adoc[logger.adoc]

The logger class is responsible for logging the console output into a txt file.

* The log(String str) method append a new line to the log file and displays it in the console
* The log file is latestlog.txt at the root of the program

.Logger class
[source, C++]
----
class Logger
{
public:
    void log(String str);
    
private:
    FileType logfile;
};

void Logger::log(String str)
{
    logfile.append(str);
    std::cout<<str<<std::endl;
}
----



== Game class

This is the master class of the game.

It is responsible of:

* initializing the game by loading user settings (returns 1 if something went wrong)
* handling the game loop
* handling the different screens
* passing the inputs
* updating the screens
* rendering the screens

.Game class
[source, C++]
----
class Game
{
public:
    Game();
    int init();
    void run();

private:
    void processEvents();
    void update();
    void render();

private:
    sf::RenderWindow mWindow;
};
----


