== Widget

//link:widgets/widget.adoc[widget.adoc]

=== Files:

* link:../../include/Widgets/Widget.h[include/Widgets/Widget.h]

* link:../../src/Widgets/Widget.cpp[src/Widgets/Widget.cpp]

=== The Widget class:

* is abstract

* represent a GUI element

* stores a vector of children widgets

* stores a pointer to parent widget

* can be drawn which also draw children

* implements SFML Transformable, Drawable and NonCopyable base classes

* defines base virtual methods for children

* has static method to make parent

.Widget class
[source, C++]
----
class Widget : public sf::Transformable, public sf::Drawable, private sf::NonCopyable
{
public:
    Widget(Anchors::Flags anchor = Anchors::Default);

private:
    // ... methods to manage the widget's children
    void attachChild(Widget* child);
    void detachChild(Widget* child);

    // ... methods to manage the widget's parent
    Widget* getParent();
    void setParent(Widget* parent);
    
public:
    void update();
    void updateTransform();
    void setAnchor(Anchors::Flags anchor);
    virtual sf::FloatRect getBoundingRect() const;
    sf::Vector2f getGlobalPosition();

protected:
    virtual void draw(sf::RenderTarget& target, sf::RenderStates states) const override;
    virtual void onDraw(sf::RenderTarget& target, sf::RenderStates states) const = 0;
    virtual void onUpdate();
    virtual void onUpdateTransform() = 0;
    Anchors::Flags mAnchor;
    Widget* mParent;
    std::vector<Widget*> mChildren;
};
----

=== The Anchors flags and functions:

* anchors flags specify anchor type hrozontally and vertically

* anchors flags are binary flags to allow binary operations

* the anchor function set widget position based on anchor flag and render target

.anchor function
[source, C++]
----
void Anchors::anchor(Widget& widget, const RenderTarget& target, Anchors::Flags flag);
----

=== Widget class hierarchy

* Widget

** VBoxLayout

** HBoxLayout

** AProgressBar

*** ShapeProgressBar

*** SpriteProgressBar

** AButton

*** SpriteButton

*** TextButton